trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: my agent pool
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
    - task: assembly-changer@1
      inputs:
        AssemblyDescription: Student  Task
        AssemblyCompany: Nave Maor
        AssemblyProduct: Sort App
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'naveProjectNew/naveProjectNew/naveProjectNew.csproj'
      displayName: 'Build Solution'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'naveProjectNew/naveProjectNew/naveProjectNew.csproj'
        zipAfterPublish: false
        modifyOutputPath: false
      displayName: 'Publish Artifacts'
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**\bin\**'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    - task: PublishPipelineArtifact@0
      displayName: 'Publish pipeline artifact'
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)'


